### ISSUE TITLE
NN programmieren

### ISSUE THREAD

**Issue by malvela** [JHamudi/BatchProcesses-AutomaticProductFeaturesCollection#12]

**Comment by malvela** [comment]
SSD, RCNN...
Pretrained models: https://keras.io/api/applications/

**Comment by malvela** [comment]
@mircoeil Bitte kurz zusammenfassen und ggf. Issue schliessen?

**Comment by mircoeil** [comment]
Genutzte Anleitung für das SSD model: https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html
Pretrained models: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md
