### ISSUE TITLE
Sing up auf https://tracker-2baa0.firebaseapp.com/signup  geht nicht. Wie kann ich mich anmelden?

### ISSUE THREAD

**Issue by malvela** [JHamudi/BatchProcesses-AutomaticProductFeaturesCollection#23]

**Comment by JHamudi** [comment]
Beim Sign up wird die mail und ihr passwort einmalig angelegt und damit kann man sich dann einloggen.
Auf Firebase wird mit angezeigt, dass ihre mail malvela@uni-bremen.de registriert ist.
Das Passwort kann ich nicht einsehen, aber mit der mail und ihr festgelegtes passwort, müssten sie sich im login bereich einloggen können

**Comment by malvela** [comment]
> Beim Sign up wird die mail und ihr passwort einmalig angelegt und damit kann man sich dann einloggen. Auf Firebase wird mit angezeigt, dass ihre mail [malvela@uni-bremen.de](mailto:malvela@uni-bremen.de) registriert ist. Das Passwort kann ich nicht einsehen, aber mit der mail und ihr festgelegtes passwort, müssten sie sich im login bereich einloggen können

es hat geklappt, danke!
