### ISSUE TITLE
Link zu dem Code über Front-End ist nicht aktuell

### ISSUE THREAD

**Issue by malvela** [JHamudi/BatchProcesses-AutomaticProductFeaturesCollection#25]
The complete code to the website and tracker is open source and can be found here.

**Comment by JHamudi** [comment]
Genau, ich muss die aktuelle Version immer wieder manuell deployen, damit sie auf firebase erreichbar ist.
Das geht leider nicht automatisch, aber ich werde noch rechtzeitig eine aktuelle version zur verfügung stellen
