### ISSUE TITLE
KiPro- und EcoKI- Projekte und nicht das alte Fu2 Projekt im Front-End

### ISSUE THREAD

**Issue by malvela** [JHamudi/BatchProcesses-AutomaticProductFeaturesCollection#28]
https://www.ecoki.de/
http://www.kipro-projekt.de/

**Comment by malvela** [comment]
Änderungen wurden nicht vorgenommen.
![image](https://user-images.githubusercontent.com/68553692/135983219-e95a7388-46d6-4cd1-ab24-c4d7917fdac7.png)

**Comment by JHamudi** [comment]
Die änderungen sind gerade nur lokal sichtbar, ich werde das heute abend deployen
