### ISSUE TITLE
Landing Page fertigstellen bzw. externe Anbindung

### ISSUE THREAD

**Issue by malvela** [JHamudi/BatchProcesses-AutomaticProductFeaturesCollection#4]

**Comment by malvela** [comment]
wie kann ich die Landingpage aufrufen?

**Comment by JHamudi** [comment]
Das muss noch eingerichtet werden, aktuell geht das nur Lokal

**Comment by malvela** [comment]
bitte den Link auch hier verfügbar machen

**Comment by JHamudi** [comment]
https://tracker-2baa0.web.app/Menu
